stages:
  - build
  - push

variables:
  IMAGE_NAME: "ourwebsite"
  DOCKERFILE_PATH: "Dockerfile"
  DOCKER_CONTEXT: "."
  DOCKER_TLS_CERTDIR: ""

default:
  tags:
    - local
  image: docker:27
  services:
    - name: docker:27-dind

build_image:
  stage: build
  script:
    - docker build -f "$DOCKERFILE_PATH" -t "$IMAGE_NAME:$CI_COMMIT_SHORT_SHA" "$DOCKER_CONTEXT"
    - docker save "$IMAGE_NAME:$CI_COMMIT_SHORT_SHA" -o image.tar
  artifacts:
    paths:
      - image.tar
    expire_in: 1 day
  rules:
    - if: '$CI_COMMIT_BRANCH'
  when: manual


push_image:
  stage: push
  when: manual
  dependencies: [build_image]
  before_script:
    - apk add --no-cache curl jq
  script:
    - set -euo pipefail
    - docker version
    - docker load -i image.tar

    # sanity: vault reachable
    - echo "VAULT_ADDR=[$VAULT_ADDR]"
    - curl -sS --fail -o /dev/null -w "health_http=%{http_code}\n" "$VAULT_ADDR/v1/sys/health"

    # Vault AppRole login -> VAULT_TOKEN
    # Vault AppRole login -> VAULT_TOKEN
    - |
      LOGIN_JSON="$(curl -sS --fail --request POST \
        --data "{\"role_id\":\"$VAULT_ROLE_ID\",\"secret_id\":\"$VAULT_SECRET_ID\"}" \
        "$VAULT_ADDR/v1/auth/approle/login")"

      echo "$LOGIN_JSON" | jq -r '{lease: .auth.lease_duration, token_present: (.auth.client_token != null)}'

      VAULT_TOKEN="$(echo "$LOGIN_JSON" | jq -r .auth.client_token)"
      test -n "$VAULT_TOKEN" && [ "$VAULT_TOKEN" != "null" ]

    # Read dockerhub creds from KV v2
    - |
      CREDS_JSON="$(curl -sS --fail -H "X-Vault-Token: $VAULT_TOKEN" \
        "$VAULT_ADDR/v1/secret/data/dockerhub")"

      echo "$CREDS_JSON" | jq -r '{version: .data.metadata.version, keys: (.data.data|keys)}'

      DOCKERHUB_USERNAME="$(echo "$CREDS_JSON" | jq -r .data.data.username)"
      DOCKERHUB_TOKEN="$(echo "$CREDS_JSON" | jq -r .data.data.token)"

      echo "USER=$DOCKERHUB_USERNAME"
      echo "TOKEN_LEN=${#DOCKERHUB_TOKEN}"
      echo "TOKEN_PREFIX=$(echo "$DOCKERHUB_TOKEN" | cut -c1-9)"

      test -n "$DOCKERHUB_USERNAME" && [ "$DOCKERHUB_USERNAME" != "null" ]
      test -n "$DOCKERHUB_TOKEN" && [ "$DOCKERHUB_TOKEN" != "null" ]

    - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

    - FULL_IMAGE="${DOCKERHUB_USERNAME}/${IMAGE_NAME}"
    - docker tag "$IMAGE_NAME:$CI_COMMIT_SHORT_SHA" "$FULL_IMAGE:$CI_COMMIT_SHORT_SHA"
    - docker push "$FULL_IMAGE:$CI_COMMIT_SHORT_SHA"

    - |
      if [ "$CI_COMMIT_BRANCH" = "main" ]; then
        docker tag "$IMAGE_NAME:$CI_COMMIT_SHORT_SHA" "$FULL_IMAGE:latest"
        docker push "$FULL_IMAGE:latest"
      fi
  rules:
    - if: '$CI_COMMIT_BRANCH'