stages:
  - build
  - push

variables:
  IMAGE_NAME: "ourwebsite"          # لازم lowercase
  DOCKERFILE_PATH: "Dockerfile"
  DOCKER_CONTEXT: "."
  DOCKER_HOST: "unix:///var/run/docker.sock"
  DOCKER_TLS_CERTDIR: ""            # مهم مع docker images أحيانًا

default:
  tags: [local]
  image: docker:27

build_image:
  stage: build
  script:
    - docker info
    - docker build -f "$DOCKERFILE_PATH" -t "$IMAGE_NAME:$CI_COMMIT_SHORT_SHA" "$DOCKER_CONTEXT"
    - docker save "$IMAGE_NAME:$CI_COMMIT_SHORT_SHA" -o image.tar
  artifacts:
    paths: [image.tar]
    expire_in: 1 day

push_image:
  stage: push
  dependencies: [build_image]
  before_script:
    - apk add --no-cache curl jq
  script:
    - docker load -i image.tar

    - |
      VAULT_TOKEN="$(curl -s --request POST \
        --data "{\"role_id\":\"$VAULT_ROLE_ID\",\"secret_id\":\"$VAULT_SECRET_ID\"}" \
        "$VAULT_ADDR/v1/auth/approle/login" | jq -r .auth.client_token)"

    - |
      DOCKERHUB_USERNAME="$(curl -s -H "X-Vault-Token: $VAULT_TOKEN" \
        "$VAULT_ADDR/v1/kv/data/dockerhub" | jq -r .data.data.username)"

    - |
      DOCKERHUB_TOKEN="$(curl -s -H "X-Vault-Token: $VAULT_TOKEN" \
        "$VAULT_ADDR/v1/kv/data/dockerhub" | jq -r .data.data.token)"

    - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

    - FULL_IMAGE="${DOCKERHUB_USERNAME}/${IMAGE_NAME}"
    - docker tag "$IMAGE_NAME:$CI_COMMIT_SHORT_SHA" "$FULL_IMAGE:$CI_COMMIT_SHORT_SHA"
    - docker push "$FULL_IMAGE:$CI_COMMIT_SHORT_SHA"

    - |
      if [ "$CI_COMMIT_BRANCH" = "main" ]; then
        docker tag "$IMAGE_NAME:$CI_COMMIT_SHORT_SHA" "$FULL_IMAGE:latest"
        docker push "$FULL_IMAGE:latest"
      fi
